name: Environemnt Variables
on:
  workflow_dispatch:

env:
    BASE_l_ENV_URL: "My Name is noman"

jobs:
  echo_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo Variables Name
        run: echo $BASE_l_ENV_URL
      - name: Echo env
        run: echo ${{ secrets.stage.BASE_ENV_URL }}